const diplomacyLandRegions = [
    ["Spa", "in"],
    ["Port", "ugal"],
    ["Gasc", "ony"],
    ["Burg", "undy"],
    ["Par", "is"],
    ["Pic", "ardy"],
    ["Br", "est"],
    ["Norm", "andy"],
    ["Belg", "ium"],
    ["R", "uhr"],
    ["Holl", "and"],
    ["Ki", "el"], 
    ["Berl", "in"],
    ["Mun", "ich"],
    ["Pruss", "ia"],
    ["Sil", "esia"],
    ["Liv", "onia"],
    ["Wars", "aw"],
    ["Gal", "icia"],
    ["Ukr", "aine"],
    ["Mos", "cow"],
    ["St. P", "etersburg"],
    ["Finl", "and"],
    ["Swed", "en"],
    ["Norw", "ay"],
    ["Denm", "ark"],
    ["Yorksh", "ire"],
    ["Wal", "es"],
    ["Edinb", "urgh"],
    ["Clyd", "eside"],
    ["Lond", "on"],
    ["Liverp", "ool"],
    ["North", "umberland"],
    ["Piedm", "ont"],
    ["Tusc", "any"],
    ["Ven", "ice"],
    ["Rom", "e"],
    ["Nap", "les"],
    ["Apul", "ia"],
    ["Tyrol", "ia"],
    ["Vien", "na"],
    ["Budap", "est"],
    ["Tri", "este"],
    ["Serb", "ia"],
    ["Alb", "ania"],
    ["Gre", "ece"],
    ["Bulg", "aria"],
    ["Rum", "ania"],
    ["Sevast", "opol"],
    ["Armen", "ia"],
    ["Syr", "ia"],
    ["Smyr", "na"],
    ["Ank", "ara"],
    ["Const", "antinople"]
  ];
  
  function getRandomRegionName() {
    let firstPart = random(diplomacyLandRegions)[0];
    let secondPart = random(diplomacyLandRegions)[1];
    return firstPart + secondPart;
  }